### ISSUE TITLE
What version of your torchmertic library is?

### ISSUE THREAD

**Issue by guoqincode** [yanivbenny/dual_diffusion#2]
When I run compute_fid.py,Something went wrong:

**AttributeError: module 'torchmetrics' has no attribute 'FID'**

I tried torchmetrics with versions 0.7.0, 0.8.0, 0.9.0, and 0.10.0, but all failed

**Comment by guoqincode** [comment]
**I solved this problem by installing torchmertic==0.60, but I still had problems loading the model:**

> python compute_fid.py --model_path experiments\dual_ddpm_cifar10_32\1xjjn9pr\checkpoints\epoch=9-step=3899.ckpt --num_timesteps 1000
Loading model...
Traceback (most recent call last):
  File "compute_fid.py", line 58, in <module>
    ddpm = DDPM.load_from_checkpoint(args.model_path, save_hyperparameters=False)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\pytorch_lightning\core\saving.py", line 156, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\pytorch_lightning\core\saving.py", line 198, in _load_model_state
    model = cls(**_cls_kwargs)
  File "C:\Users\qguo\All_ai_code\dual_diffusion\src\ddpm.py", line 35, in __init__
    out_channels=self.conf.model.out_channels,
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\dictconfig.py", line 357, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\base.py", line 190, in _format_and_raise
    format_and_raise(
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\dictconfig.py", line 445, in _get_impl
    return self._resolve_with_default(
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\basecontainer.py", line 65, in _resolve_with_default
    resolved_node = self._maybe_resolve_interpolation(
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\base.py", line 616, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\base.py", line 482, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\base.py", line 662, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\antlr4\tree\Tree.py", line 34, in visit
    return tree.accept(self)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\grammar\gen\OmegaConfGrammarParser.py", line 205, in accept
    return visitor.visitConfigValue(self)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\antlr4\tree\Tree.py", line 34, in visit
    return tree.accept(self)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\grammar\gen\OmegaConfGrammarParser.py", line 339, in accept
    return visitor.visitText(self)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\grammar_visitor.py", line 298, in visitText
    return self.visitInterpolation(c)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\antlr4\tree\Tree.py", line 34, in visit
    return tree.accept(self)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\grammar\gen\OmegaConfGrammarParser.py", line 1030, in accept
    return visitor.visitInterpolationResolver(self)
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\grammar_visitor.py", line 179, in visitInterpolationResolver
    return self.resolver_interpolation_callback(
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\base.py", line 648, in resolver_interpolation_callback
    return self._evaluate_custom_resolver(
  File "C:\Users\qguo\anaconda3\envs\dual\lib\site-packages\omegaconf\base.py", line 599, in _evaluate_custom_resolver
    **raise UnsupportedInterpolationType(
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type out_channels
    full_key: model.out_channels
    object_type=dict**

**Comment by yanivbenny** [comment]
Sorry for the trouble. This is indeed torchmetrics 0.6.0, we will add that the the readme.

About the other problem. It appears like an omegaconf failure.
We have added a fix.
